# Site settings
ref: CSCC09
title: Programming on the Web
edition: Fall 2025
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.me/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/utoronto.ca/fall2025/cscc09
feedback: https://forms.gle/F2Wy25YiVMhyFrWd9

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: TBD
  location: IA 4124
  contact: Piazza only (no email)
  role: Prof.

assistants:
    # - name: Anabelle Hsiao
    #   contact: Piazza only
    #   hours: Monday 1-2 PM
    #   location: IC 402

timings:
    - section: LEC01
      time: Wednesay 11:00-13:00
      location: HW 215
      instructor: Thierry Sans
    - section: LEC02
      time: Wednesday 14:00-16:00
      location: HW 215
      instructor: Thierry Sans

first: 20250901